#38 - updating to Laravel 8
brewmap/brewmap pull request #46
Opened 2020-09-09 05:01 UTC by krzysztofrewak

This should close #38 but not before `psalm/plugin-laravel` will be updated (eg with this: https://github.com/psalm/psalm-plugin-laravel/pull/112).

Plus I need to investigate why `User::factory()->...` is not working. Right now I needed to use syntax `UserFactory::new()->...`

2020-09-09 12:15 UTC, krzysztofrewak commented
@mateuszchodor, please check if I added intl correctly. It was required by new Nova.

2020-09-09 16:55 UTC, mateuszchodor requested changes

2020-09-09 16:55 UTC, mateuszchodor commented on environment/docker/php/Dockerfile
> +    && apk add --no-cache php7-pear php7-dev php7-intl gcc musl-dev make icu-dev
I think we don't need to install the php7-intl, as you enabled intl extension a few lines below in the code.

2020-09-09 16:55 UTC, mateuszchodor commented on environment/docker/php/Dockerfile
>  RUN docker-php-ext-install mysqli pdo pdo_mysql json
I would suggest to move docker-ext-configure right here and move intl to other extesions install part

2020-09-10 06:08 UTC, mateuszchodor approved these changes

2020-09-10 06:15 UTC, merged